name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda
      with:
        gradle-version: '8.7'  # Specify the Gradle version here

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: my-artifact # Set the artifact name (optional)
        path: build/libs # Path to the artifact, adjust accordingly
        if-no-files-found: warn # Set behavior if no files are found (optional)
        retention-days: 30 # Set retention duration (optional)
        compression-level: 6 # Set compression level (optional)
        overwrite: false # Set overwrite behavior (optional)
